run:
    path: /run
    controller: App\Controller\ProcessingController::run
    methods:    POST
    format:      json

status:
    path: /status/{id}
    controller: App\Controller\ProcessingController::status
    methods:    GET
    format:      json